
diff ../test_sub_hw4/apps/models.py  ./apps/models.py
diff ../test_sub_hw4/apps/simple_ml.py ./apps/simple_ml.py 
diff ../test_sub_hw4/python/needle/backend_ndarray/__init__.py ./python/needle/backend_ndarray/__init__.py
diff ../test_sub_hw4/python/needle/backend_ndarray/ndarray.py ./python/needle/backend_ndarray/ndarray.py
diff ../test_sub_hw4/python/needle/backend_ndarray/ndarray_backend_numpy.py ./python/needle/backend_ndarray/ndarray_backend_numpy.py
diff ../test_sub_hw4/python/needle/data/datasets/__init__.py ./python/needle/data/datasets/__init__.py 
diff ../test_sub_hw4/python/needle/data/datasets/ptb_dataset.py ./python/needle/data/datasets/ptb_dataset.py 
diff ../test_sub_hw4/python/needle/data/datasets/cifar10_dataset.py ./python/needle/data/datasets/cifar10_dataset.py 
diff ../test_sub_hw4/python/needle/data/datasets/mnist_dataset.py ./python/needle/data/datasets/mnist_dataset.py 
diff ../test_sub_hw4/python/needle/data/datasets/ndarray_dataset.py ./python/needle/data/datasets/ndarray_dataset.py 
diff ../test_sub_hw4/python/needle/data/datasets/ptb_dataset.py ./python/needle/data/datasets/ptb_dataset.py 
diff ../test_sub_hw4/python/needle/data/__init__.py ./python/needle/data/__init__.py
diff ../test_sub_hw4/python/needle/data/data_basic.py ./python/needle/data/data_basic.py
diff ../test_sub_hw4/python/needle/data/data_transforms.py ./python/needle/data/data_transforms.py
diff ../test_sub_hw4/python/needle/init/__init__.py ./python/needle/init/__init__.py
diff ../test_sub_hw4/python/needle/init/init_initializers.py ./python/needle/init/init_initializers.py
diff ../test_sub_hw4/python/needle/init/init_basic.py ./python/needle/init/init_basic.py
diff ../test_sub_hw4/python/needle/nn/__init__.py ./python/needle/nn/__init__.py
diff ../test_sub_hw4/python/needle/nn/nn_basic.py ./python/needle/nn/nn_basic.py 
diff ../test_sub_hw4/python/needle/nn/nn_conv.py ./python/needle/nn/nn_conv.py
diff ../test_sub_hw4/python/needle/nn/nn_sequence.py ./python/needle/nn/nn_sequence.py 
diff ../test_sub_hw4/python/needle/ops/__init__.py ./python/needle/ops/__init__.py
diff ../test_sub_hw4/python/needle/ops/ops_logarithmic.py ./python/needle/ops/ops_logarithmic.py
diff ../test_sub_hw4/python/needle/ops/ops_mathematic.py ./python/needle/ops/ops_mathematic.py
diff ../test_sub_hw4/python/needle/ops/ops_tuple.py ./python/needle/ops/ops_tuple.py
diff ../test_sub_hw4/python/needle/__init__.py ./python/needle/__init__.py
diff ../test_sub_hw4/python/needle/autograd.py ./python/needle/autograd.py
diff ../test_sub_hw4/python/needle/backend_numpy.py ./python/needle/backend_numpy.py
diff ../test_sub_hw4/python/needle/backend_selection.py ./python/needle/backend_selection.py
diff ../test_sub_hw4/python/needle/optim.py ./python/needle/optim.py 
diff ../test_sub_hw4/src/ndarray_backend_cpu.cc ./src/ndarray_backend_cpu.cc
diff ../test_sub_hw4/src/ndarray_backend_cuda.cu ./src/ndarray_backend_cuda.cu
